<?php

/**
 * Colombia places
 *
 * @author   Saul Morales Pacheco <moralespachecopablo@gmail.com>
 * @version  1.1.33
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['CO'] = array(
	'AMZ' => array(
        "EL ENCANTO",
        "LA CHORRERA",
        "LA PEDRERA",
        "LA VICTORIA",
        "MIRITI - PARANA",
        "LETICIA",
        "PUERTO ALEGRIA",
        "PUERTO ARICA",
        "PUERTO NARINO",
        "PUERTO SANTANDER",
        "TARAPACA"
		),
	'ANT' => array(
        "ABEJORRAL",
        "ABRIAQUI",
        "ALEJANDRIA",
        "AMAGA",
        "AMALFI",
        "ANDES",
        "ANGELOPOLIS",
        "ANGOSTURA",
        "ANORI",
        "SANTAFE DE ANTIOQUIA",
        "ANZA",
        "APARTADO",
        "ARBOLETES",
        "ARGELIA",
        "ARMENIA",
        "BARBOSA",
        "BELLO",
        "BELMIRA",
        "BETANIA",
        "BETULIA",
        "CIUDAD BOLIVAR",
        "BRICENO",
        "BURITICA",
        "CACERES",
        "CAICEDO",
	"CALDAS",
        "CAMPAMENTO",
        "CANASGORDAS",
        "CARACOLI",
        "CARAMANTA",
        "CAREPA",
        "CAROLINA",
        "CAUCASIA",
        "CHIGORODO",
        "CISNEROS",
        "COCORNA",
        "CONCEPCION",
        "CONCORDIA",
	"COPACABANA",
        "DABEIBA",
        "EL CARMEN DE VIBORAL",
        "EL SANTUARIO",
        "DON MATIAS",
        "EBEJICO",
        "EL BAGRE",
        "ENTRERRIOS",
	"ENVIGADO",
        "FREDONIA",
        "FRONTINO",
        "GIRALDO",
	"GIRARDOTA",
        "GOMEZ PLATA",
        "GRANADA",
        "GUADALUPE",
	"GUARNE",
        "GUATAPE",
        "HELICONIA",
        "HISPANIA",
	"ITAGUI",
        "ITUANGO",
        "JARDIN",
        "JERICO",
        "LA CEJA",
	"LA ESTRELLA",
        "LA PINTADA",
        "LA UNION",
        "LIBORINA",
        "MACEO",
        "MARINILLA",
        "MEDELLIN",
        "MONTEBELLO",
        "MURINDO",
        "MUTATA",
        "NARINO",
        "NECOCLI",
        "NECHI",
        "OLAYA",
        "ENOL",
        "PEQUE",
        "PUEBLORRICO",
        "PUERTO BERRIO",
        "PUERTO NARE",
        "PUERTO TRIUNFO",
        "SABANETA",
        "REMEDIOS",
        "RETIRO",
	"RIONEGRO",
        "SABANALARGA",
        "SALGAR",
        "SAN ANDRES",
        "SAN CARLOS",
        "SAN FRANCISCO",
        "SAN JERONIMO",
        "SAN JOSE DE LA MONTANA",
        "SAN JUAN DE URABA",
        "SAN JUAN DE URABA",
        "SAN PEDRO",
        "SAN PEDRO DE URABA",
        "SAN RAFAEL",
        "SAN ROQUE",
        "SANTA BARBARA",
        "SANTA ROSA DE OSOS",
        "SANTO DOMINGO",
        "SAN VICENTE",
        "SEGOVIA",
        "SONSON",
        "SOPETRAN",
        "TAMESIS",
        "TARAZA",
        "TARSO",
        "TITIRIBI",
        "TOLEDO",
        "TURBO",
        "URAMITA",
        "URRAO",
        "VALDIVIA",
        "VALPARAISO",
        "VEGACHI",
        "VENECIA",
        "YALI",
        "VIGIA DEL FUERTE",
        "YARUMAL",
        "YOLOMBO",
        "YONDO",
        "BOLOMBO",
        "ALTAMIRA",
        "CURRULAO",
        "DORADAL",
        "EL DOCE",
        "EL PENOL",
        "EL TIGRE",
        "EL TRES",
        "LA CRUZADA",
        "LA SIERRA",
        "LA TABLAZA",
        "LLANADAS",
        "LLANOS DE CUIVA",
        "NUEVA COLONIA",
        "PALERMO",
        "PALMITAS",
        "PEQUE",
        "PUERTO BELGICA",
        "PUERTO VALDIVIA",
        "SAN ANTONIO PRADO",
        "SAN MIGUEL",
        "SANTA ELENA",
        "SANTA ISABELL",
        "SANTIAGO",
        "SEVILLA",
        "VERSALLES",
        "ZUNGO CARRETERA",
        "JARDIN CACARES",
        "JARDIN SUROESTE",
        "ZARAGOZA"
		),
	'ARU' => array(
        "ARAUCA",
        "ARAUQUITA",
        "CRAVO NORTE",
        "FORTUL",
        "PUERTO RONDON",
        "SARAVENA",
        "LA ESMERALDA",
        "LA PESQUERA",
        "PUERTO NARINO",
        "TAME"
		),
	'ATL' => array(
        "BARANOA",
        "BARRANQUILLA",
        "CAMPO DE LA CRUZ",
        "CANDELARIA",
        "GALAPA",
        "JUAN DE ACOSTA",
        "LURUACO",
        "MALAMBO",
        "MANATI",
        "PALMAR DE VARELA",
        "PIOJO",
        "POLONUEVO",
        "PONEDERA",
        "PUERTO COLOMBIA",
        "REPELON",
        "SABANAGRANDE",
        "SABANALARGA",
        "SANTA LUCIA",
        "SANTO TOMAS",
        "SOLEDAD",
        "SUAN",
        "TUBARA",
        "ARROYO DE PIEDRA",
        "JUAN MINA",
        "ISABEL LOPEZ",
        "LA PENA",
        "MOLINEROS",
        "PLAYA MENDOZA",
        "PUERTO GIRALDO",
        "SALGAR",
        "CAMPECHE",
        "SANTA VERONICA",
        "USIACURI"
		),
	'BOG' => array(
	    "BOGOTA D.C."
    ),
	'BOL' => array(
        "ACHI",
        "ALTOS DEL ROSARIO",
        "ARENAL",
        "ARJONA",
        "ARROYOHONDO",
        "BARRANCO DE LOBA",
        "CALAMAR",
        "CANTAGALLO",
        "CARTAGENA",
        "CICUCO",
        "CLEMENCIA",
        "CORDOBA",
        "EL CARMEN DE BOLIVAR",
        "EL GUAMO",
        "EL PENON",
        "HATILLO DE LOBA",
        "MAGANGUE",
        "MAHATES",
        "MARGARITA",
        "MARIA LA BAJA",
        "MOMPOS",
        "MONTECRISTO",
        "MORALES",
        "PINILLOS",
        "REGIDOR",
        "RIO VIEJO",
        "SAN CRISTOBAL",
        "SAN ESTANISLAO",
        "SAN FERNANDO",
        "SAN JACINTO",
        "SAN JACINTO DEL CAUCA",
        "SAN JUAN NEPOMUCENO",
        "SAN MARTIN DE LOBA",
        "SAN PABLO",
        "SANTA CATALINA",
        "SANTA ROSA",
        "SANTA ROSA DEL SUR",
        "SIMITI",
        "SOPLAVIENTO",
        "TALAIGUA NUEVO",
        "TIQUISIO",
        "TURBACO",
        "TURBANA",
        "VILLANUEVA",
        "BALLESTAS",
        "BARU",
        "BAYUNCA",
        "BUENA SENA",
        "GALERAZAMBA",
        "JUAN ARIAS",
        "LA BOQUILLA",
        "LOMA DE ARENA",
        "NOROSI",
        "PASACABALLOS",
        "PONTEZUELA",
        "SANTA ANA",
        "ZAMBRANO"
		),
	'BOY' => array(
        "ALMEIDA",
        "AQUITANIA",
        "ARCABUCO",
        "BELEN",
        "BERBEO",
        "BETEITIVA",
        "BOAVITA",
        "BOYACA",
        "BRICENO",
        "BUENAVISTA",
        "BUSBANZA",
        "CALDAS",
        "CAMPOHERMOSO",
        "CERINZA",
        "CHINAVITA",
        "CHIQUINQUIRA",
        "CHIQUIZA",
        "CHISCAS",
        "CHITA",
        "CHITARAQUE",
        "CHIVATA",
        "CHIVOR",
        "CIENEGA",
        "COMBITA",
        "COPER",
        "CORRALES",
        "COVARACHIA",
        "CUBARA",
        "CUCAITA",
        "CUITIVA",
        "DUITAMA",
        "EL COCUY",
        "EL ESPINO",
        "FIRAVITOBA",
        "FLORESTA",
        "GACHANTIVA",
        "GAMEZA",
        "GARAGOA",
        "GUACAMAYAS",
        "GUATEQUE",
        "GUAYATA",
        "GUICAN",
        "IZA",
        "JENESANO",
        "JERICO",
        "LABRANZAGRANDE",
        "LA CAPILLA",
        "LA UVITA",
        "LA VICTORIA",
        "MACANAL",
        "MARIPI",
        "MIRAFLORES",
        "MONGUA",
        "MONGUI",
        "MONIQUIRA",
        "MOTAVITA",
        "MUZO",
        "NOBSA",
        "NUEVO COLON",
        "OICATA",
        "OTANCHE",
        "PACHAVITA",
        "PAEZ",
        "PAIPA",
        "PAJARITO",
        "PANQUEBA",
        "PAUNA",
        "PAYA",
        "PAZ DE RIO",
        "PESCA",
        "PISBA",
        "PUERTO BOYACA",
        "QUIPAMA",
        "RAMIRIQUI",
        "RAQUIRA",
        "RONDON",
        "SABOYA",
        "SACHICA",
        "SAMACA",
        "SAN EDUARDO",
        "SAN JOSE DE PARE",
        "SAN LUIS DE GACENO",
        "SAN MATEO",
        "SAN MATEO",
        "SAN PABLO DE BORBUR",
        "SANTA MARIA",
        "SANTANA",
        "SANTA ROSA DE VITERBO",
        "SANTA SOFIA",
        "SATIVANORTE",
        "SATIVASUR",
        "SIACHOQUE",
        "SOATA",
        "SOCHA",
        "SOCOTA",
        "SOGAMOSO",
        "SOMONDOCO",
        "SORA",
        "SORACA",
        "SOTAQUIRA",
        "SUSACON",
        "SUTAMARCHAN",
        "SUTATENZA",
        "TASCO",
        "TENZA",
        "TIBANA",
        "TIBASOSA",
        "TINJACA",
        "TIPACOQUE",
        "TOCA",
        "TOGUI",
        "TOPAGA",
        "TOTA",
        "TUNJA",
        "TUNUNGUA",
        "TURMEQUE",
        "TUTA",
        "TUTAZA",
        "UMBITA",
        "VENTAQUEMADA",
        "VILLA DE LEYVA",
        "VIRACACHA",
        "BELENCITO",
        "COSCUEZ",
        "NARINO",
        "PANTANO DE VARGAS",
        "PUENTE BOYACA",
        "PUERTO SERVIEZ",
        "SANTA BARBARA",
        "ZETAQUIRA"
		),
	'CAL' => array(
        "AGUADAS",
        "ANSERMA",
        "ARANZAZU",
        "BELALCAZAR",
        "CHINCHINA",
        "FILADELFIA",
        "LA DORADA",
        "LA MERCED",
        "MANZANARES",
        "MANIZALES",
        "MARMATO",
        "MARQUETALIA",
        "MARULANDA",
        "NEIRA",
        "NORCASIA",
        "PACORA",
        "PALESTINA",
        "PENSILVANIA",
        "RIOSUCIO",
        "RISARALDA",
        "SALAMINA",
        "SAMANA",
        "SAN JOSE",
        "SUPIA",
        "VICTORIA",
        "VILLAMARIA",
        "ARAUCA",
        "ARBOLEDA",
        "ARMA",
        "BOLIVIA",
        "BONAFONT",
        "CASTILLA",
        "FLORENCIA",
        "GUARINOCITO",
        "LA FELISA",
        "MONTEBONITO",
        "SAMARIA",
        "SAN BARTOLOME",
        "SAN DANIEL",
        "SAN DIEGO",
        "SAN FELIX",
        "VITERBO"
		),
	'CAQ' => array(
        "ALBANIA",
        "BELEN DE LOS ANDAQUIES",
        "CARTAGENA DEL CHAIRA",
        "CURILLO",
        "EL DONCELLO",
        "EL PAUJIL",
        "FLORENCIA",
        "LA MONTANITA",
        "MILAN",
        "MORELIA",
        "PUERTO RICO",
        "SAN JOSE EL FRAGUA",
        "SAN VICENTE DEL CAGUAN",
        "SOLANO",
        "SOLITA",
        "RIONEGRO",
        "VALPARAISO"
		),
	'CAS' => array(
        "AGUAZUL",,
        "CHAMEZA",
        "HATO COROZAL",
        "LA SALINA",
        "MANI",
        "MONTERREY",
        "NUNCHIA",
        "OROCUE",
        "PAZ DE ARIPORO",
        "PORE",
        "RECETOR",
        "SABANALARGA",
        "SACAMA",
        "SAN LUIS DE PALENQUE",
        "TAMARA",
        "TAURAMENA",
        "TRINIDAD",
        "VILLANUEVA",
        "AGUACLARA",
        "ARAGUANEY",
        "CURIANA POZO",
        "LA CHAPARRERA",
        "VILLACAROLA",
        "YOPAL"
		),
	'CAU' => array(
        "ALMAGUER",
        "ARGELIA",
        "BALBOA",
        "BOLIVAR",
        "BUENOS AIRES",
        "CAJIBIO",
        "CALDONO",
        "CALOTO",
        "CORINTO",
        "EL TAMBO",
        "FLORENCIA",
        "GUAPI",
        "INZA",
        "JAMBALO",
        "LA SIERRA",
        "LA VEGA",
        "LOPEZ",
        "MERCADERES",
        "MIRANDA",
        "MORALES",
        "PADILLA",
        "PAEZ",
        "PATIA",
        "PIAMONTE",
        "PIENDAMO",
        "POPAYAN",
        "PUERTO TEJADA",
        "PURACE",
        "ROSAS",
        "SAN SEBASTIAN",
        "SANTANDER DE QUILICHAO",
        "SANTA ROSA",
        "SILVIA",
        "SOTARA",
        "SUAREZ",
        "SUCRE",
        "TIMBIO",
        "TIMBIQUI",
        "TORIBIO",
        "TOTORO",
        "GUACHENE",
        "VILLA RICA"
		),
	'CES' => array(
        "AGUACHICA",
        "AGUSTIN CODAZZI",
        "ASTREA",
        "BECERRIL",
        "BOSCONIA",
        "CHIMICHAGUA",
        "CHIRIGUANA",
        "CURUMANI",
        "EL COPEY",
        "EL PASO",
        "GAMARRA",
        "GONZALEZ",
        "LA GLORIA",
        "LA JAGUA DE IBIRICO",
        "LA PAZ",
        "MANAURE",
        "PAILITAS",
        "PELAYA",
        "PUEBLO BELLO",
        "RIO DE ORO",
        "SAN ALBERTO",
        "SAN DIEGO",
        "SAN MARTIN",
        "AMALAMEQUE",
        "ARJONA",
        "AYACUCHO",
        "CARACOLICITO",
        "CODAZZI",
        "LA LOMA",
        "RINCON HONDO",
        "SAN ROQUE",
        "VALLEDUPAR"
		),
	'CHO'  => array(
        "ACANDI",
        "ALTO BAUDO",
        "ATRATO",
        "BAGADO",
        "BAHIA SOLANO",
        "BAJO BAUDO",
        "BELEN DE BAJIRA",
        "BOJAYA",
        "EL CANTON DEL SAN PABLO",
        "CARMEN DEL DARIEN",
        "CERTEGUI",
        "CONDOTO",
        "EL CARMEN DE ATRATO",
        "EL LITORAL DEL SAN JUAN",
        "ISTMINA",
        "JURADO",
        "LLORO",
        "MEDIO ATRATO",
        "MEDIO BAUDO",
        "MEDIO SAN JUAN",
        "NOVITA",
        "NUQUI",
        "RIO QUITO",
        "RIO IRO",
        "RIOSUCIO",
        "SAN JOSE DEL PALMAR",
        "SIPI",
        "TADO",
        "QUIBDO",
        "UNGUIA",
        "GUARATO",
        "QUIBDO",
        "YUTO",
        "ANDAGOYA",
        "ANIMAS",
        "CAPURGANA",
        "SANTA MARIA DEL DERIEN",
        "UNION PANAMERICANA"
		),
	'COR' => array(
        "AYAPEL",
        "BUENAVISTA",
        "CANALETE",
        "CERETE",
        "CHIMA",
        "CHINU",
        "CIENAGA DE ORO",
        "COTORRA",
        "LA APARTADA",
        "LORICA",
        "LOS CORDOBAS",
        "MOMIL",
        "MONITOS",
        "MONTELIBANO",
        "MONTERIA",
        "PLANETA RICA",
        "PUEBLO NUEVO",
        "PUERTO ESCONDIDO",
        "PUERTO LIBERTADOR",
        "PURISIMA",
        "SAHAGUN",
        "SAN ANDRES SOTAVENTO",
        "SAN ANTERO",
        "SAN BERNARDO DEL VIENTO",
        "SAN CARLOS",
        "SAN PELAYO",
        "TIERRALTA",
        "CARILLO",
        "COLOMBOY",
        "EL CARITO",
        "EL VARAL",
        "EL VIAJANO",
        "LA YE",
        "SAN SEBASTIAN",
        "SAN JOSE DE URE",
        "TUCHIN",
        "VILLA FATIMA",
        "VALENCIA"
		),
	'CUN' => array(
        "AGUA DE DIOS",
        "ALBAN",
        "ANAPOIMA",
        "ANOLAIMA",
        "APULO",
        "ARBELAEZ",
        "BELTRAN",
        "BITUIMA",
        "BOJACA",
        "CABRERA",
        "CACHIPAY",
        "CAJICA",
        "CAPARRAPI",
        "CAQUEZA",
        "CARMEN DE CARUPA",
        "CHAGUANI",
        "CHIA",
        "CHIPAQUE",
        "CHOACHI",
        "CHOCONTA",
        "COGUA",
        "COTA",
        "CUCUNUBA",
        "EL COLEGIO",
        "EL PENON",
        "EL ROSAL",
        "FACATATIVA",
        "FOMEQUE",
        "FOSCA",
        "FUNZA",
        "FUQUENE",
        "FUSAGASUGA",
        "GACHALA",
        "GACHANCIPA",
        "GACHETA",
        "GAMA",
        "GIRARDOT",
        "GRANADA",
        "GUACHETA",
        "GUADUAS",
        "GUASCA",
        "GUATAQUI",
        "GUATAVITA",
        "GUAYABAL DE SIQUIMA",
        "GUAYABETAL",
        "GUTIERREZ",
        "JERUSALEN",
        "JUNIN",
        "LA CALERA",
        "LA MESA",
        "LA PALMA",
        "LA PENA",
        "LA VEGA",
        "LENGUAZAQUE",
        "MACHETA",
        "MADRID",
        "MANTA",
        "MEDINA",
        "MOSQUERA",
        "NARINO",
        "NEMOCON",
        "NILO",
        "NIMAIMA",
        "NOCAIMA",
        "PACHO",
        "PAIME",
        "PANDI",
        "PARATEBUENO",
        "PASCA",
        "PUERTO SALGAR",
        "PULI",
        "QUEBRADANEGRA",
        "QUETAME",
        "QUIPILE",
        "RICAURTE",
        "SAN ANTONIO DEL TEQUENDAM",
        "SAN BERNARDO",
        "SAN CAYETANO",
        "SAN FRANCISCO",
        "SAN JUAN DE RIO SECO",
        "SASAIMA",
        "SESQUILE",
        "SIBATE",
        "SILVANIA",
        "SIMIJACA",
        "SOACHA",
        "SUBACHOQUE",
        "SUESCA",
        "SUPATA",
        "SUSA",
        "SUTATAUSA",
        "TABIO",
        "TAUSA",
        "TENA",
        "TENJO",
        "TIBACUY",
        "TIBIRITA",
        "TOCAIMA",
        "TOCANCIPA",
        "TOPAIPI",
        "UBALA",
        "UBAQUE",
        "VILLA DE SAN DIEGO DE UBA",
        "UNE",
        "UTICA",
        "VENECIA",
        "VERGARA",
        "VIANI",
        "VILLAGOMEZ",
        "VILLAPINZON",
        "VILLETA",
        "VIOTA",
        "YACOPI",
        "ZIPACON",
        "BRICENO",
        "CAMBAO",
        "CEPELLANIA",
        "CARTAGENA",
        "CHUNAUTA",
        "CHUSACA",
        "EL CARQUITO",
        "EL SISGA",
        "EL TRIUNFO",
        "LA FLORIDA",
        "LA GRAN VIDA",
        "LA UNION",
        "LA VICTORIA",
        "MAYA",
        "PUENTE PIEDRA",
        "PUENTE QUETAME",
        "PUERTO BOGOTA",
        "SANTANDERSITO",
        "SOPO",
        "SUBIA",
        "TOBIA",
        "TUDELA",
        "UBATE",
        "ZIPAQUIRA"
		),
	'GUA' => array(
        "CACAHUAL",
        "INIRIDA",
        "BARRANCO MINAS",
        "MAPIRIPANA",
        "MORICHAL",
        "PANA PANA",
        "PUERTO COLOMBIA",
        "LA GUADALUPE",
        "GUAVIARE",
        "SAN FELIPE"
		),
	'GUV' => array(
        "CALAMAR",
        "EL RETORNO",
        "MIRAFLORES",
        "SAN JOSE DEL GUAVIARE"
		),
	'HUI' => array(
        "ACEVEDO",
        "AGRADO",
        "AIPE",
        "ALGECIRAS",
        "ALTAMIRA",
        "LA ARGENTINA",
        "BARAYA",
        "CAMPOALEGRE",
        "COLOMBIA",
        "ELIAS",
        "GARZON",
        "GIGANTE",
        "UADALUPE",
        "HOBO",
        "IQUIRA",
        "LA PLATA",
        "NATAGA",
        "NEIVA",
        "OPORAPA",
        "PAICOL",
        "PALERMO",
        "PALESTINA",
        "PITAL",
        "PITALITO",
        "RIVERA",
        "SALADOBLANCO",
        "SAN AGUSTIN",
        "ISNOS",
        "SANTA MARIA",
        "SUAZA",
        "TARQUI",
        "TELLO",
        "TERUEL",
        "TESALIA",
        "TIMANA",
        "VILLAVIEJA",
        "BELENCITO",
        "BRUSELAS",
        "SAN ADOLFO",
        "VEGALARGA",
        "YAGUARA"
		),
	'GUJ' => array(
        "ALBANIA",
        "BARRANCAS",
        "DIBULLA",
        "DISTRACCION",
        "EL MOLINO",
        "FONSECA",
        "HATONUEVO",
        "LA JAGUA DEL PILAR",
        "MAICAO",
        "MANAURE",
        "RIOHACHA",
        "SAN JUAN DEL CESAR",
        "URIBIA",
        "URUMITA",
        "BUENAVISTA",
        "MINGUEO",
        "VILLANUEVA"
		),
	'MAG' => array(
        "ALGARROBO",
        "ARACATACA",
        "ARIGUANI",
        "CERRO SAN ANTONIO",
        "CHIBOLO",
        "CIENAGA",
        "CONCORDIA",
        "EL BANCO",
        "EL PINON",
        "EL RETEN",
        "FUNDACION",
        "GUAMAL",
        "NUEVA GRANADA",
        "PEDRAZA",
        "PIJINO DEL CARMEN",
        "PIVIJAY",
        "PLATO",
        "PUEBLOVIEJO",
        "REMOLINO",
        "SABANAS DE SAN ANGEL",
        "SALAMINA",
        "SAN SEBASTIAN DE BUENAVIS",
        "SANTA ANA",
        "SANTA BARBARA DE PINTO",
        "SANTA MARTA",
        "SAN ZENON",
        "SITIONUEVO",
        "TENERIFE",
        "ZAPAYAN",
        "GAIRA",
        "EL DIFICIL",
        "GUACAMAYAL",
        "GUAIMARO",
        "LA GRAN VIA",
        "MEDIA LUNA",
        "ORIHUECA",
        "PALERMO",
        "MEDIA LUNA",
        "ORIHUECA",
        "PRADO SEVILLA",
        "PUEBLONUEVO",
        "RIOFRIO",
        "SAN FERNANDO",
        "TAGANGA",
        "TUCURINCA",
        "ZONA BANANERA"
		),
	'MET' => array(
        "ACACIAS",
        "BARRANCA DE UPIA",
        "CABUYARO",
        "CASTILLA LA NUEVA",
        "CUBARRAL",
        "CUMARAL",
        "EL CALVARIOL",
        "EL CASTILLO",
        "EL DORADO",
        "FUENTE DE ORO",
        "GRANADA",
        "GUAMAL",
        "MAPIRIPAN",
        "MESETASL",
        "LA MACARENA",
        "PUERTO CONCORDIA",
        "PUERTO GAITAN",
        "PUERTO LLERAS",
        "PUERTO LOPEZ",
        "PUERTO RICO",
        "RESTREPO",
        "SAN CARLOS DE GUAROA",
        "SAN JUAN DE ARAMA",
        "SAN JUANITO",
        "SAN MARTIN",
        "URIBE",
        "LEJANIAS",
        "VILLAVICENCIO",
        "APIAY",
        "PACHAQUIAROM",
        "VISTAHERMOSA"
		),
	'NAR' => array(
        "ALBAN",
        "ALDANA",
        "ARBOLEDA", 
        "ANCUYA",
        "BARBACOAS",
        "BELEN",
        "BUESACO",
        "COLON",
        "CONSACA",
        "CONTADERO",
        "CORDOBA",
        "CUASPUD",
        "CUMBAL",
        "CUMBITARA",
        "COVENAS",
        "EL CHARCO",
        "EL PENOL",
        "EL ROSARIO",
        "EL TABLON DE GOMEZ",
        "EL TAMBO",
        "FUNES",
        "GUACHUCAL",
        "GUAITARILLA",
        "GUALMATAN",
        "ILES",
        "IMUES",
        "IPIALES",
        "LA CRUZ",
        "LA LLANADA",
        "LA TOLA",
        "LA UNION",
        "LEIVA",
        "LINARES",
        "LOS ANDES",
        "MAGUI",
        "MALLAMA",
        "MOSQUERA",
        "NARINO",
        "OLAYA HERRERA",
        "OSPINA",
        "FRANCISCO PIZARRO",
        "PASTO",
        "POLICARPA",
        "POTOSI",
        "PROVIDENCIA",
        "PUERRES",
        "PUPIALES",
        "RICAURTE",
        "ROBERTO PAYAN",
        "SAMANIEGO",
        "SAN BERNARDO",
        "SANDONA",
        "SAN LORENZO",
        "SAN PABLO",
        "SAN PEDRO DE CARTAGO",
        "SANTA BARBARA",
        "SANTACRUZ",
        "SAPUYES",
        "TAMINANGO",
        "TANGUA",
        "TUMACO",
        "TUQUERRES",
        "ALTAQUER",
        "BUESAQUILLO",
        "BORUECOS ARBOLEDA",
        "CABRERA",
        "CAJAPI",
        "CANDELILLAS",
        "CARLOSAMA  CUASPUD",
        "CATAMBUCO",
        "CEBADAL",
        "CHACHAGUI",
        "CHUCUNES",
        "DAZA",
        "EL ESPINO",
        "EL ENCANO",
        "EL DIVISO",
        "EL REMOLINO",
        "ESPRIELLA",
        "GENOVA",
        "GENOY",
        "GUACHAVEZ SAN CRUZ",
        "IMBILI",
        "JUNIN",
        "JOSE MARIA HERNANDEZ",
        "LA FLORIDA",
        "LA GUAYACANA",
        "LAS LAJAS",
        "MOCONDINO",
        "LLORENTE",
        "OBONUCO",
        "PIEDRAHANCHA",
        "PILCUAN",
        "PINZON",
        "SAN JOSE DE ALBAN",
        "SOTOMAYOR",
        "TANGAREAL CARRETERA",
        "TANGAREAL DEL MIRA",
        "YACUANQUER"
		),
	'NOR' => array(
        "ABREGO",
        "ARBOLEDAS",
        "BOCHALEMA",
        "BUCARASICA",
        "CACHIRA",
        "CACOTA",
        "HINACOTA",
        "CHITAGA",
        "CONVENCION",
        "CUCUTA",
        "CUCUTILLA",
        "DURANIA",
        "EL CARMEN",
        "EL TARRA",
        "EL ZULIA",
        "GRAMALOTE",
        "HACARI",
        "HERRAN",
        "LABATECA",
        "LA ESPERANZA",
        "LA PLAYA",
        "LOS PATIOS",
        "LOURDES",
        "MUTISCUA",
        "OCANA",
        "PAMPLONA",
        "PAMPLONITA",
        "PUERTO SANTANDER",
        "RAGONVALIA",
        "SALAZAR",
        "SAN CALIXTO",
        "SAN CAYETANO",
        "SANTIAGO",
        "SARDINATA",
        "SILOS",
        "EORAMA",
        "TIBU",
        "TOLEDO",
        "VILLA CARO",
        "SAN BERNARDO",
        "VILLA DEL ROSARIO"
		),
	'PUT' => array(
        "COLON",
        "SAN MIGUEL",
        "MOCOA",
        "ORITO",
        "PUERTO ASIS",
        "PUERTO CAICEDO",
        "PUERTO GUZMAN",
        "LEGUIZAMO",
        "SAN FRANCISCO",
        "SANTIAGO",
        "VALLE DEL GUAMUEZ",
        "SIBUNDOY",
        "EL TIGRE",
        "LA HORMIGA - VALLE GUAMUEZ",
        "PUERTO UMBRIA",
        "SANTANA",
        "VILLAGARZON"
		),
	'SAP' => array(
        "SAN ANDRES",
        "SANTA CATALINA",
        "PROVIDENCIA"
		),
	'QUI' => array(
        "ARMENIA",
        "BUENAVISTA",
        "CALARCA",
        "CIRCASIA",
        "CORDOBA",
        "FILANDIA",
        "GENOVA",
        "LA TEBAIDA",
        "MONTENEGRO",
        "PIJAO",
        "QUIMBAYA",
        "SALENTO"
		),
	'RIS' => array(
        "PEREIRA",
        "APIA",
        "BALBOA",
        "BELEN DE UMBRIA",
        "DOSQUEBRADAS",
        "GUATICA",
        "LA CELIA",
        "LA VIRGINIA",
        "MARSELLA",
        "MISTRATO",
        "PUEBLO RICO",
        "QUINCHIA",
        "SANTA ROSA DE CABAL",
        "IRRA",
        "PEREIRA",
        "SAN CLEMENTE",
        "SANTUARIO"
		),
	'SAN'  => array(
        "AGUADA",
        "ALBANIA",
        "ARATOCA",
        "BARBOSA",
        "BARICHARA",
        "BARRANCABERMEJA",
        "BETULIA",
        "BOLIVAR",
        "CABRERA",
        "CALIFORNIA",
        "BUCARAMANGA",
        "CAPITANEJO",
        "CARCASI",
        "CEPITA",
        "CERRITO",
        "CHARALA",
        "CHARTA",
        "CHIMA",
        "CHIPATA",
        "CIMITARRA",
        "CONCEPCION",
        "CONFINES",
        "CONTRATACION",
        "COROMORO",
        "CURITI",
        "EL CARMEN DE CHUCURI",
        "EL GUACAMAYO",
        "EL PENON",
        "EL PLAYON",
        "ENCINO",
        "ENCISO",
        "FLORIAN",
        "FLORIDABLANCA",
        "GALAN",
        "GAMBITA",
        "GIRON",
        "GUACA",
        "GUADALUPE",
        "GUAPOTA",
        "GUAVATA",
        "GUEPSA",
        "HATO",
        "JESUS MARIA",
        "JORDAN",
        "LA BELLEZA",
        "LANDAZURI",
        "LA PAZ",
        "LEBRIJA",
        "LOS SANTOS",
        "MACARAVITA",
        "MALAGA",
        "MATANZA",
        "MOGOTES",
        "MOLAGAVITA",
        "OIBA",
        "OCAMONTE",
        "ONZAGA",
        "PARAMO",
        "PALMAR",
        "PIEDECUESTA",
        "PINCHOTE",
        "PUENTE NACIONAL",
        "PALMAS DEL SOCORRO",
        "PUERTO PARRA",
        "PUERTO WILCHES",
        "RIONEGRO",
        "SABANA DE TORRES",
        "SAN ANDRES",
        "SAN BENITO",
        "SAN GIL",
        "SAN JOAQUIN",
        "SAN JOSE DE MIRANDA",
        "SAN MIGUEL",
        "SANTA HELENA DEL OPON",
        "SAN VICENTE DE CHUCURI",
        "SANTA BARBARA",
        "SIMACOTA",
        "SOCORRO",
        "SUAITA",
        "SUCRE",
        "SURATA",
        "TONA",
        "VETAS",
        "VALLE DE SAN JOSE",
        "VELEZ",
        "VILLANUEVA",
        "OLIVAL",
        "PESCADERO",
        "PUERTO ARAUJO",
        "VADO REAL",
        "ZAPATOCA"
		),
	'SUC' => array(
        "BUENAVISTA",
        "CAIMITO",
        "COLOSO",
        "COROZAL",
        "COVENAS",
        "CHALAN",
        "EL ROBLE",
        "GALERAS",
        "GUARANDA",
        "LA UNION",
        "LOS PALMITOS",
        "MAJAGUAL",
        "MORROA",
        "OVEJAS",
        "PALMITO",
        "SAMPUES",
        "SAN BENITO ABAD",
        "SAN JUAN DE BETULIA",
        "SAN MARCOS",
        "SAN ONOFRE",
        "SAN PEDRO",
        "SINCELEJO",
        "SINCE",
        "SUCRE",
        "SANTIAGO DE TOLU",
        "TOLU VIEJO"
		),
	'TOL' => array(
        "ALPUJARRA",
        "ALVARADO",
        "AMBALEMA",
        "ANZOATEGUI",
        "ARMERO",
        "ATACO",
        "CAJAMARCA",
        "CARMEN DE APICALA",
        "CASABIANCA",
        "CHAPARRAL",
        "COELLO",
        "COYAIMA",
        "CUNDAY",
        "DOLORES",
        "ESPINAL",
        "FALAN",
        "FLANDES",
        "FRESNO",
        "GUAMO",
        "HERVEO",
        "HONDA",
        "IBAGUE",
        "ICONONZO",
        "LERIDA",
        "LIBANO",
        "MARIQUITA",
        "MELGAR",
        "MURILLO",
        "NATAGAIMA",
        "ORTEGA",
        "PALOCABILDO",
        "PIEDRAS",
        "PLANADAS",
        "PRADO",
        "PURIFICACION",
        "RIOBLANCO",
        "RONCESVALLES",
        "ROVIRA",
        "SALDANA",
        "SAN ANTONIO",
        "SAN LUIS",
        "SANTA ISABEL",
        "SUAREZ",
        "VALLE DE SAN JUAN",
        "VENADILLO",
        "VILLAHERMOSA",
        "BOQUERON",
        "BUENOS AIRES",
        "CALDAS VIEJO",
        "CASTILLA",
        "CHENCHE ASOLEADO",
        "CHICORAL",
        "COELLO-COCORA",
        "CONVENIO",
        "DOIMA",
        "EL LIMON",
        "EL TABLAZO",
        "EL TOTUMO",
        "GAITANIA",
        "GUALANDAY",
        "HERRERA",
        "JUNIN",
        "JUNTAS",
        "LA ARADA",
        "LA CHAMBA",
        "LA PALMITA",
        "LA SIERRA",
        "PLAYA HERRERA",
        "PADUA",
        "PASTALES NUEVO",
        "PASTALES VIEJO",
        "PAYANDE",
        "PLAYARRICA",
        "SAN FELIPE",
        "SANTA TERESA",
        "SANTIAGO PEREZ",
        "TRES ESQUINAS",
        "VELU",
        "VILLARESTREPO",
        "VILLARRICA"
		),
	'VAC' => array(
        "ALCALA",
        "ANDALUCIA",
        "ANSERMANUEVO",
        "ARGELIA",
        "BOLIVAR",
        "BUENAVENTURA",
        "GUADALAJARA DE BUGA",
        "BUGALAGRANDE",
        "CAICEDONIA",
        "CALI",
        "CALIMA",
        "CANDELARIA",
        "CARTAGO",
        "DAGUA",
        "EL AGUILA",
        "EL CAIRO",
        "EL CERRITO",
        "EL DOVIO",
        "FLORIDA",
        "GINEBRA",
        "GUACARI",
        "JAMUNDI",
        "LA CUMBRE",
        "LA UNION",
        "LA VICTORIA",
        "OBANDO",
        "PALMIRA",
        "PRADERA",
        "RESTREPO",
        "RIOFRIO",
        "ROLDANILLO",
        "SAN PEDRO",
        "SEVILLA",
        "TORO",
        "TRUJILLO",
        "TULUA",
        "ULLOA",
        "VERSALLES",
        "VIJES",
        "YOTOCO",
        "YUMBO",
        "BUGA",
        "LA PAILA",
        "ZARZAL"
		),
	'VAU' => array(
        "PACOA",
        "CARURU",
        "MITU",
        "PAPUNAUA",
        "TARAIRA",
        "ACARICAURA",
        "TIO BARBAS",
        "YAVARATE"
	    ),
	'VIC' => array(
        "CUMARIBO",
        "LA PRIMAVERA",
        "PUERTO CARRENO",
        "SANTA ROSALIA"
		)
	);
